name: EAS Build

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    name: Build Android and iOS apps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_EXPO_TOKEN_SPIKETEAMS }}

      - name: Install dependencies
        run: npm install
    
      - name: Get config file
        env:
          GOOGLE_SERVICES_64: ${{ secrets.EAS_GOOGLE_PLAY_API }}
        run: |
          echo $GOOGLE_SERVICES_64 > google-services.json.b64
          base64 -d -i google-services.json.b64 > google-services.json

      - name: Build and submit
        run: EXPO_APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.EAS_APPLE_APP_SPECIFIC_PASSWORD }} eas build --platform all --non-interactive --profile production --non-interactive --auto-submit-with-profile=production --no-wait